import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes, useParams } from 'react-router-dom';
import SystemDiagram from './SystemDiagram.js';

const SVG = '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
    + '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n'
    + '<!-- Generated by graphviz version 9.0.0 -->\n'
    + '<svg width="200pt" height="100pt" viewBox="0.00 0.00 200.00 100.00" xmlns="http://www.w3.org/2000/svg">'
    + '<g id="graph0" class="graph"><g id="node1" class="node"><title>CD-ANT-9001-A</title>'
    + '<polygon fill="#d9ead3" stroke="black" points="0,0 10,0 10,10 0,10"/>'
    + '<text x="5" y="5">CD-ANT-9001-A</text></g></g></svg>';

function ComponentStub() {
    const { name } = useParams();
    return <div>COMPONENT {name}</div>;
}

function renderPage() {
    return render(
        <MemoryRouter initialEntries={['/system-diagram']}>
            <Routes>
                <Route path="/system-diagram" element={<SystemDiagram />} />
                <Route path="/component/:name" element={<ComponentStub />} />
            </Routes>
        </MemoryRouter>
    );
}

test('inlines the server SVG, zooms with the buttons, and opens a component on click', async () => {
    global.fetch = jest.fn(() => Promise.resolve({
        ok: true, status: 200, statusText: 'OK', text: () => Promise.resolve(SVG),
    }));
    renderPage();

    const content = await screen.findByTestId('diagram-content');
    expect(global.fetch).toHaveBeenCalledWith('/padloper/api/system_diagram.svg');
    expect(content.querySelector('svg')).not.toBeNull();
    expect(content.innerHTML.startsWith('<svg')).toBe(true); // prologue and doctype dropped

    expect(screen.getByTestId('zoom-level')).toHaveTextContent('100%');
    userEvent.click(screen.getByRole('button', { name: 'zoom in' }));
    expect(screen.getByTestId('zoom-level')).toHaveTextContent('125%');
    expect(content.style.transform).toMatch(/scale\(1\.25\)/);
    userEvent.click(screen.getByRole('button', { name: '100%' }));
    expect(screen.getByTestId('zoom-level')).toHaveTextContent('100%');

    // Download links point at the API.
    expect(screen.getByRole('link', { name: 'SVG' })).toHaveAttribute('href', '/padloper/api/system_diagram.svg');
    expect(screen.getByRole('link', { name: 'DOT' })).toHaveAttribute('href', '/padloper/api/system_diagram.dot');

    userEvent.click(content.querySelector('g.node polygon'));
    expect(await screen.findByText('COMPONENT CD-ANT-9001-A')).toBeInTheDocument();
});

test('a drag is not treated as a click', async () => {
    global.fetch = jest.fn(() => Promise.resolve({
        ok: true, status: 200, statusText: 'OK', text: () => Promise.resolve(SVG),
    }));
    renderPage();
    const content = await screen.findByTestId('diagram-content');
    const viewport = screen.getByTestId('diagram-viewport');
    const node = content.querySelector('g.node polygon');

    // Simulate a pan: down, move, up, then the click the browser fires afterwards.
    fireEvent.mouseDown(viewport, { button: 0, clientX: 0, clientY: 0 });
    fireEvent.mouseMove(viewport, { clientX: 40, clientY: 25 });
    fireEvent.mouseUp(viewport);
    fireEvent.click(node, { clientX: 40, clientY: 25 });
    await waitFor(() => expect(content.style.transform).toMatch(/translate\(40px, 25px\)/));
    // Still on the diagram page: the pan did not open the component.
    expect(screen.queryByText(/^COMPONENT/)).not.toBeInTheDocument();
    expect(screen.getByTestId('diagram-viewport')).toBeInTheDocument();
});

test('shows the server error when Graphviz is unavailable', async () => {
    global.fetch = jest.fn(() => Promise.resolve({
        ok: false, status: 503, statusText: 'Service Unavailable',
        text: () => Promise.resolve(JSON.stringify({ error: 'Graphviz is not installed on the server' })),
    }));
    renderPage();
    expect(await screen.findByText('Graphviz is not installed on the server')).toBeInTheDocument();
});
