FROM python:3.8-slim-buster

WORKDIR /

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./flask-interface /flask-interface
COPY ./padloper /padloper
COPY ./flask-interface/.flaskenv ./flask-interface/flaskenv

ENV DB_HOST="ws://janusgraph"
CMD ["gunicorn", "--bind", "0.0.0.0:4300", "flask-interface.app:app"]
